=== aliciacbu/PubSemWebBiblissimaMSS/XML_Pivot_DeuxiemeBonDeCommande.dtd
<!ELEMENT HasFeature (#PCDATA | FeatureType | Page | Canvas | Descriptor | Caption | Rubrique | Inscription | Note | Record)*>
<!ATTLIST HasFeature id CDATA #IMPLIED>
<!ELEMENT Subidentifier (#PCDATA)>
<!ELEMENT Explicit (#PCDATA)>
<!ELEMENT Page (#PCDATA)>
<!ATTLIST Page unit CDATA #IMPLIED>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT Thumbnail (#PCDATA)>
<!ELEMENT DigitalSurrogate (#PCDATA)>
<!ATTLIST DigitalSurrogate type CDATA #IMPLIED>
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang CDATA #IMPLIED>
<!ELEMENT Identifier (#PCDATA | Idno | Subidentifier | Volume)*>
<!ATTLIST Identifier type CDATA #IMPLIED>
<!ELEMENT Inscription (#PCDATA)>
<!ELEMENT AssociatedWork (#PCDATA | Title | Concept)*>
<!ATTLIST AssociatedWork id_bbma CDATA #IMPLIED>
<!ATTLIST AssociatedWork id CDATA #IMPLIED>
<!ATTLIST AssociatedWork uri CDATA #IMPLIED>
<!ELEMENT Book (#PCDATA | Concept | ObjectType | Shelfmark | Name | Text | Participant | Date | Place | DigitalSurrogate | Manifest | Thumbnail | Record | Extent | Format | BibliographicReference | Term | Note | HasPart | HasFeature | RelatedManifestation | InventoryPage | Canvas | InventorySection)*>
<!ATTLIST Book state CDATA #IMPLIED>
<!ATTLIST Book uri CDATA #IMPLIED>
<!ATTLIST Book id CDATA #IMPLIED>
<!ELEMENT RelatedText (#PCDATA)>
<!ELEMENT Work (#PCDATA | Title | AltTitle | Title_Bbma | Text | Concept | Note | Record | Repertory | RelatedWork)*>
<!ATTLIST Work id CDATA #IMPLIED>
<!ATTLIST Work id_bbma CDATA #IMPLIED>
<!ELEMENT Title_Bbma (#PCDATA)>
<!ATTLIST Title_Bbma lang CDATA #IMPLIED>
<!ELEMENT Idno (#PCDATA)>
<!ELEMENT Concept (#PCDATA)>
<!ATTLIST Concept uri CDATA #IMPLIED>
<!ATTLIST Concept source CDATA #IMPLIED>
<!ELEMENT GroupDigitalSurrogates (#PCDATA | DigitalSurrogate)*>
<!ELEMENT GroupBooks (#PCDATA | Shelfmark | Name | Record | Text | Participant | HasPart | Note)*>
<!ELEMENT InventorySection (#PCDATA)>
<!ELEMENT Manifestation (#PCDATA | Date | Place | Text | HasPart | Participant | Format | Note | BibliographicReference | Record | Book | GroupDigitalSurrogates)*>
<!ATTLIST Manifestation id CDATA #IMPLIED>
<!ATTLIST Manifestation state CDATA #IMPLIED>
<!ELEMENT Canvas (#PCDATA)>
<!ELEMENT RelatedConcept (#PCDATA)>
<!ATTLIST RelatedConcept type CDATA #IMPLIED>
<!ELEMENT Rubrique (#PCDATA)>
<!ELEMENT Term (#PCDATA)>
<!ATTLIST Term context CDATA #IMPLIED>
<!ATTLIST Term id CDATA #IMPLIED>
<!ATTLIST Term uri CDATA #IMPLIED>
<!ELEMENT City (#PCDATA)>
<!ATTLIST City id CDATA #IMPLIED>
<!ATTLIST City geonames CDATA #IMPLIED>
<!ELEMENT Edition (#PCDATA)>
<!ELEMENT Pages (#PCDATA)>
<!ATTLIST Pages unit CDATA #IMPLIED>
<!ELEMENT GenericTerm (#PCDATA)>
<!ELEMENT Participant (#PCDATA | Name | Identifier | AltName | Name_Bbma | Concept | Birth | Death | QualifiedTitle | Gender | Residence | Occupation | Note | Record)*>
<!ATTLIST Participant id_bbma CDATA #IMPLIED>
<!ATTLIST Participant id CDATA #IMPLIED>
<!ATTLIST Participant role CDATA #IMPLIED>
<!ELEMENT RecordList (#PCDATA | DataBase | Book | Manifestation | GroupBooks | Participant | Place | Work | Repository | Collection)*>
<!ELEMENT Volume (#PCDATA)>
<!ELEMENT Note (#PCDATA)>
<!ELEMENT Descriptor (#PCDATA | Name | Concept | RelatedConcept)*>
<!ATTLIST Descriptor id CDATA #IMPLIED>
<!ELEMENT Death (#PCDATA | Date | Place)*>
<!ELEMENT Country (#PCDATA)>
<!ATTLIST Country id CDATA #IMPLIED>
<!ATTLIST Country geonames CDATA #IMPLIED>
<!ELEMENT Collection (#PCDATA | Concept | Name | Type | Participant | Book | Inventory | Record | Note)*>
<!ATTLIST Collection state CDATA #IMPLIED>
<!ELEMENT RelatedManifestation (#PCDATA)>
<!ATTLIST RelatedManifestation id CDATA #IMPLIED>
<!ELEMENT Repertory (#PCDATA)>
<!ELEMENT Inventory (#PCDATA | Title | DigitalSurrogate | Manifest | Record)*>
<!ATTLIST Inventory id CDATA #IMPLIED>
<!ELEMENT PartType (#PCDATA)>
<!ATTLIST PartType id CDATA #IMPLIED>
<!ELEMENT FeatureType (#PCDATA)>
<!ATTLIST FeatureType id CDATA #IMPLIED>
<!ELEMENT Extent (#PCDATA)>
<!ATTLIST Extent unit CDATA #IMPLIED>
<!ELEMENT Shelfmark (#PCDATA | Organisation | Identifier)*>
<!ELEMENT HasPart (#PCDATA | PartType | Pages | Text | Participant | Date | Place | Format | Term | Record | Note | HasFeature | Book)*>
<!ATTLIST HasPart id CDATA #IMPLIED>
<!ELEMENT Birth (#PCDATA | Date | Place)*>
<!ELEMENT DataBase (#PCDATA)>
<!ATTLIST DataBase uri CDATA #IMPLIED>
<!ELEMENT Incipit (#PCDATA)>
<!ELEMENT ObjectType (#PCDATA)>
<!ATTLIST ObjectType uri CDATA #IMPLIED>
<!ELEMENT Format (#PCDATA)>
<!ATTLIST Format unit CDATA #IMPLIED>
<!ATTLIST Format uri CDATA #IMPLIED>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language type CDATA #IMPLIED>
<!ATTLIST Language uri CDATA #IMPLIED>
<!ATTLIST Language id CDATA #IMPLIED>
<!ELEMENT QualifiedTitle (#PCDATA)>
<!ELEMENT Record (#PCDATA)>
<!ATTLIST Record id CDATA #IMPLIED>
<!ATTLIST Record root CDATA #IMPLIED>
<!ELEMENT InventoryPage (#PCDATA)>
<!ATTLIST InventoryPage invID CDATA #IMPLIED>
<!ATTLIST InventoryPage unit CDATA #IMPLIED>
<!ELEMENT AltTitle (#PCDATA)>
<!ATTLIST AltTitle lang CDATA #IMPLIED>
<!ELEMENT Organisation (#PCDATA)>
<!ATTLIST Organisation id CDATA #IMPLIED>
<!ATTLIST Organisation id_bbma CDATA #IMPLIED>
<!ELEMENT Name_Bibma (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title lang CDATA #IMPLIED>
<!ELEMENT Text (#PCDATA | Title | AssociatedWork | Language | Incipit | Explicit | Note | Edition | Participant)*>
<!ATTLIST Text id CDATA #IMPLIED>
<!ELEMENT Residence (#PCDATA)>
<!ATTLIST Residence id CDATA #IMPLIED>
<!ATTLIST Residence geonames CDATA #IMPLIED>
<!ELEMENT Century (#PCDATA)>
<!ELEMENT Manifest (#PCDATA)>
<!ELEMENT BibliographicReference (#PCDATA)>
<!ELEMENT Date (#PCDATA | Century | Year | Note)*>
<!ATTLIST Date uri CDATA #IMPLIED>
<!ATTLIST Date type CDATA #IMPLIED>
<!ELEMENT Caption (#PCDATA | GenericTerm | RelatedText)*>
<!ELEMENT Name_Bbma (#PCDATA)>
<!ATTLIST Name_Bbma lang CDATA #IMPLIED>
<!ELEMENT Occupation (#PCDATA)>
<!ATTLIST Occupation id CDATA #IMPLIED>
<!ELEMENT Repository (#PCDATA | Concept | RelatedConcept | Name | AltName | Name_Bibma | Country | City | Organisation | Note)*>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ATTLIST Year uri CDATA #IMPLIED>
<!ELEMENT AltName (#PCDATA)>
<!ATTLIST AltName lang CDATA #IMPLIED>
<!ELEMENT Place (#PCDATA | Name | Concept | RelatedConcept | AltName | Name_Bbma | Note)*>
<!ATTLIST Place type CDATA #IMPLIED>
<!ATTLIST Place geonames CDATA #IMPLIED>
<!ATTLIST Place id CDATA #IMPLIED>
<!ELEMENT RelatedWork (#PCDATA)>
<!ATTLIST RelatedWork id CDATA #IMPLIED>
<!ATTLIST RelatedWork type CDATA #IMPLIED>

=== aliciacbu/PubSemWebBiblissimaMSS/XML_Pivot_DeuxiemeBonDeCommande.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RecordList SYSTEM "file:/Users/stefaniegehrke/Documents/Dumps_locales_portail/XML_Pivot_DeuxiemeBonDeCommande.dtd">
<RecordList>   
    <DataBase uri="[URI database here]">[Name of the database]</DataBase>     
        <Book id="" state="attesté or conservé">
            <Concept source="BnF etc.">[to be added by Biblissima]</Concept>
            <ObjectType uri="">['Manuscrit', 'Manuscrit enluminé', 'incunabula', 'incunable']</ObjectType>
            <Shelfmark>[Shelfmark goes here] 
                <Organisation id="">[Name of the Organisation that keeps the manuscript goes here]</Organisation>
                <Identifier type="">
                    <Idno>[Shelfmark]</Idno>
                    <Subidentifier>[Subidentifier]</Subidentifier>
                    <Volume>[Number of volume]</Volume>
                </Identifier>
                <Identifier type="canonical">[Shelfmark as used by holding organisation goes here]</Identifier>
            </Shelfmark>
            <Name lang="[internal language ID database]">[a special name for the manuscript or incunabula or item in general goes here]</Name>
            <Text id="">
                <Title lang="[internal language ID database]">[the title of the text goes here]</Title>
                <AssociatedWork id="" id_bbma="">
                    <Title lang="[internal language ID database]">[the title of the work goes here]</Title>
                </AssociatedWork>
                <Language id="" uri="" type="">[Language of the text]</Language>
                <Incipit>[Incipit]</Incipit>
                <Explicit>[Explicit]</Explicit>
                <Note>[Note]</Note>
            </Text>
            <Participant id="" role="[marc role or definition]" id_bbma="">
                <Name lang="[internal language ID database]"></Name>
            </Participant>
            <Date uri=""><Century>[Century]</Century><Year uri="">[YYYY]</Year><Note></Note></Date>
            <Place id="" type="[historical or precise]">
                <Name lang="[internal language ID database]">[the name of the place goes here]</Name>
            </Place>
            <DigitalSurrogate type="[integral or partial]">[URL of the digital surrogate goes here]</DigitalSurrogate>
            <Manifest>[URL of manifest Shared Canvas goes here]</Manifest>
            <Thumbnail>[URL of Thumbnail goes here]</Thumbnail>
            <Record id="" root="">[URL of the record goes here]</Record>
            <Extent unit="[f or p or NP]">[number of folios or pages goes here]</Extent>
            <Format unit="mm" uri="">[height x width of a page/folio goes here]</Format>
            <BibliographicReference>[Bibliographic Reference goes here]</BibliographicReference>
            <Term context="[some indication about the type of terms you provide]" id="" uri="">[Term goes here]</Term>
            <Note></Note>
            <HasPart id="">
                <PartType id="">[e.g. textual unit, artistique unit, codicological unit, binding etc.]</PartType>
                <Pages unit="[f or p or NP]">[folios or folio / pages or page go here]</Pages>
                <Text id="">
                    <Title lang="[internal language ID database]"></Title>
                    <AssociatedWork id="" uri="[URI goes here]">
                        <Title lang="[internal language ID database]"></Title>
                    </AssociatedWork>
                    <Language id="" uri="" type=""></Language>
                    <Edition></Edition>
                    <Incipit></Incipit>
                    <Explicit></Explicit>
                    <Note></Note>
                </Text>
                <Participant id="" role="[marc role or definition]" id_bbma="">
                    <Name lang="[internal language ID database]"></Name>
                </Participant>
                <Date uri=""><Century>[Century]</Century><Year>[YYYY]</Year><Note></Note></Date>
                <Place id="">         
                    <Name lang="[internal language ID database]"></Name>     
                </Place>
                <Format unit="" uri=""></Format>
                <Term context="[support]" id="" uri=""></Term>
                <Record id="" root="">[URL notice component goes here]</Record>
                <Note></Note>
                <HasFeature id="">
                    <FeatureType id="" uri="">[the type of the feature, for example "marque de provenance" or "enluminure" goes here]</FeatureType>
                    <Page unit=""></Page>
                    <Canvas>[à remplir par Biblissima]</Canvas>
                    <Descriptor id="">
                        <Name></Name>
                        <Concept>[URL authority record Biblissima]</Concept>
                        <RelatedConcept type="">[the URL of a related Concept goes here - example : skos_broader ou la personne à laquelle une marque de provenance appartient]</RelatedConcept>
                        <AltName>[alternative name]</AltName>
                        <Context>[code Dewey]</Context>
                        <Note>[exlpanation or comment on the descriptor]</Note>
                    </Descriptor>
                    <Caption>[cpation text-string goes here]
                        <GenericTerm>[generic term if available - seulement Mandragore pour l'instant - et pas sûre si on l'affiche : certaines légendes commençant par un terme générique qui permet le regroupement dans l’index]</GenericTerm>
                        <RelatedText>[related text if available]</RelatedText>
                    </Caption>
                    <Rubrique>[Rubrique]</Rubrique>
                    <Inscription>[Inscription]</Inscription>
                    <Note>[Note]</Note>
                    <Record id="">[URL record]</Record>
                </HasFeature>
            </HasPart>
            <HasFeature id="">
                <FeatureType id=""></FeatureType>
                <Page unit=""></Page>
                <Canvas>[à remplir par Biblissima]</Canvas>
                <Descriptor id="">
                    <Name></Name>
                    <Concept>[URL authority record Biblissima]</Concept>
                    <RelatedConcept>[URL authority record Biblissima]</RelatedConcept>
                    <AltName>[alternative name]</AltName>
                    <Context>[code Dewey]</Context>
                    <Note>[exlpanation or comment on the descriptor]</Note>
                </Descriptor>
                <Caption>[cpation text-string goes here]
                    <GenericTerm>[generic term if available - seulement Mandragore pour l'instant - et pas sûre si on l'affiche : certaines légendes commençant par un terme générique qui permet le regroupement dans l’index]</GenericTerm>
                    <RelatedText>[related text if available]</RelatedText>
                </Caption>
                <Rubrique>[Rubrique]</Rubrique>
                <Inscription>[Inscription]</Inscription>
                <Note>[Note]</Note>
                <Record id="">[URL record]</Record>
            </HasFeature>
            <RelatedManifestation id="">[Only for incunabula]</RelatedManifestation>
        </Book>    

        <Manifestation id="" state="attesté"><!-- [for incunabulas only] -->
            <Date>
                <Year></Year>
            </Date>
            <Place id="">
                <Name></Name>
            </Place>
            <Text>
                <AssociatedWork>
                    <Concept></Concept>
                </AssociatedWork>
                <Title></Title>
                <Language></Language>
                <Language id="" uri="" type=""></Language>
                <Edition></Edition>
                <Incipit></Incipit>
                <Explicit></Explicit>
                <Note></Note>
            </Text>
            <HasPart>
                <PartType>textual unit</PartType>
                <Text>
                    <AssociatedWork>
                        <Concept/>
                    </AssociatedWork>
                </Text>
            </HasPart>
            <Participant id="" role="">
                <Name></Name>
            </Participant>
            <Format></Format>
            <Note></Note>
            <BibliographicReference></BibliographicReference>
            <Record></Record>
            <Book id=""></Book>
            <GroupDigitalSurrogates>
                <DigitalSurrogate></DigitalSurrogate>
            </GroupDigitalSurrogates>
        </Manifestation>
    
        <GroupBooks>
            <Shelfmark>
                <Organisation id=""></Organisation>
                <Identifier>
                    <Idno></Idno>
                    <Subidentifier></Subidentifier>
                </Identifier>
                <Identifier type="canonical">[Shelfmark as used by holding organisation goes here]</Identifier>
            </Shelfmark>
            <Name lang="[internal language ID database]"></Name>
            <Record id="" root="">[URL goes here]</Record>
            <Text id="">
                <Title lang="[internal language ID database]"></Title>
                <AssociatedWork id="" uri="[URI goes here]">
                    <Title lang="[internal language ID database]"></Title>
                </AssociatedWork>
                <Language id="" uri=""></Language>
            </Text>
            <Participant id="" role="r4010 - r610 - r70 - etc. ">
                <Name lang="[internal language ID database]"></Name><Identifier type="canonical">[Shelfmark as used by holding organisation goes here]</Identifier>
            </Participant>
            <HasPart>
                <Book id="" uri="[ARK Medium or ARK Mandragore or URI volume]"></Book>
            </HasPart>
            <Note></Note>
        </GroupBooks>

    <Participant id="" id_bbma="">
            <Name lang="[internal language ID database]"></Name>
            <AltName lang="[internal language ID database]"></AltName>
